"""initial schema

Revision ID: ce0ec588b432
Revises: 
Create Date: 2026-07-23 17:02:00.921291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce0ec588b432'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('machine_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('vmid', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=23), nullable=True),
    sa.Column('dns_record', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=120), nullable=True),
    sa.Column('operating_system_version', sa.String(length=120), nullable=True),
    sa.Column('architecture', sa.String(length=40), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('cpu', sa.String(length=200), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_value', sa.Float(), nullable=True),
    sa.Column('memory_unit', sa.String(length=10), nullable=True),
    sa.Column('disk_value', sa.Float(), nullable=True),
    sa.Column('disk_unit', sa.String(length=10), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('gpu', sa.String(length=200), nullable=True),
    sa.Column('network_interface', sa.String(length=120), nullable=True),
    sa.Column('hardware_model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("machine_type IN ('VM', 'LXC', 'PHYSICAL')", name='ck_machines_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_dns_record'), ['dns_record'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_machine_type'), ['machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_status'), ['status'], unique=False)

    op.create_table('obsidian_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('machine_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("machine_type IN ('VM', 'LXC', 'PHYSICAL')", name='ck_obsidian_templates_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_type')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('machine_type_scope', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("machine_type_scope IN ('ALL', 'VM', 'LXC', 'PHYSICAL')", name='ck_task_templates_scope'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_templates_machine_type_scope'), ['machine_type_scope'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_machine_id'), ['machine_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_machine_id', sa.Integer(), nullable=True),
    sa.Column('external_name', sa.String(length=200), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depends_on_machine_id IS NOT NULL OR external_name IS NOT NULL', name='ck_dependencies_target'),
    sa.CheckConstraint('depends_on_machine_id IS NULL OR depends_on_machine_id != machine_id', name='ck_dependencies_no_self'),
    sa.ForeignKeyConstraint(['depends_on_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'depends_on_machine_id', name='uq_dependencies_machine_pair')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_depends_on_machine_id'), ['depends_on_machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_machine_id'), ['machine_id'], unique=False)

    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['obsidian_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_documents_machine_id'), ['machine_id'], unique=False)

    op.create_table('machine_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_notes_machine_id'), ['machine_id'], unique=False)

    op.create_table('machine_tags',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_id', 'tag_id')
    )
    op.create_table('machine_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('not_applicable_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Pending', 'In Progress', 'Completed', 'Blocked', 'Not Applicable')", name='ck_machine_tasks_status'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_tasks_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_tasks_template_id'), ['template_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('port IS NULL OR (port >= 1 AND port <= 65535)', name='ck_services_port'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_machine_id'), ['machine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_machine_id'))

    op.drop_table('services')
    with op.batch_alter_table('machine_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_tasks_template_id'))
        batch_op.drop_index(batch_op.f('ix_machine_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_machine_tasks_machine_id'))
        batch_op.drop_index(batch_op.f('ix_machine_tasks_category'))

    op.drop_table('machine_tasks')
    op.drop_table('machine_tags')
    with op.batch_alter_table('machine_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_notes_machine_id'))

    op.drop_table('machine_notes')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_documents_machine_id'))

    op.drop_table('generated_documents')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_machine_id'))
        batch_op.drop_index(batch_op.f('ix_dependencies_depends_on_machine_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_machine_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_event_type'))

    op.drop_table('activity_events')
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_templates_machine_type_scope'))
        batch_op.drop_index(batch_op.f('ix_task_templates_category'))

    op.drop_table('task_templates')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    op.drop_table('obsidian_templates')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_status'))
        batch_op.drop_index(batch_op.f('ix_machines_name'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_type'))
        batch_op.drop_index(batch_op.f('ix_machines_ip_address'))
        batch_op.drop_index(batch_op.f('ix_machines_host'))
        batch_op.drop_index(batch_op.f('ix_machines_dns_record'))
        batch_op.drop_index(batch_op.f('ix_machines_archived_at'))

    op.drop_table('machines')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
